swagger:
  enable: true
  application-name: ${spring.application.name}
  application-version: 1.0
  application-description: SpringBoot template
  try-host: http://localhost:${server.port}
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
